spring.datasource.url=jdbc:sqlite:gsb-spectrum.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.threads.virtual.enabled=true
server.port=5357
spring.jackson.default-property-inclusion=non_null
